AUTOTAB_MAPPING = {
    ---ENTRANCES---
    ["SpringMeadows"] = { "Spring Meadows" },
    ["GoblusLair"] = { "Flying Waters" },
    ["AncientSanctuary"] = { "Ancient Sanctuary" },
    ["SideLevel_RedForest"] = { "Crimson Forest" },
    ["EsquieNest"] = { "Esquie's Nest" },
    ["SideLevel_OrangeForest"] = { "Falling Leaves" },
    ["SideLevel_CleasFlyingHouse"] = { "Flying Manor" },
    ["ForgottenBattlefield"] = { "Forgotten Battlefield" },
    ["SidelLevel_FrozenHearts"] = { "Frozen Hearts" },
    ["GestralVillage"] = { "Gestral Village" },
    ["MonocoStation"] = { "Monoco's Station" },
    ["Lumiere"] = { "Lumiere" },
    ["Monolith_Interior_PaintressIntro"] = { "The Monolith" },
    ["Monolith_Interior_Climb"] = { "The Monolith" },
    ["OldLumiere"] = { "Old Lumiere" },
    ["SideLevel_Reacher"] = { "The Reacher" },
    ["SideLevel_AxonPath"] = { "Renoir's Drafts" },
    ["SmallLevel_SimonArea"] = { "Renoir's Drafts" },
    ["SeaCliff"] = { "Stone Wave Cliffs" },
    ["Sirene"] = { "Sirene" },
    ["SideLevel_TwilightSanctuary"] = { "Endless Night Sanctuary" },
    ["Visages"] = { "Visages" },
    ["SideLevel_YellowForest"] = { "Yellow Harvest" },
    ["SideLevel_DarkShores"] = { "Dark Shores" },
    ["Manor"] = { "Continent", "South Continent" },
    ["Camps"] = { "Continent", "South Continent" },
    ["WorldMap"] = { "Continent" },
    ["SideLevel_VersosDraft"] = { "Continent", "South Continent", "Verso's Drafts"},


    ---EXITS---

    --South Continent
    ["EXIT_SpringMeadows"] =  { "Continent", "South Continent" },
    ["EXIT_GoblusLair"] =  { "Continent", "South Continent" },
    ["EXIT_AncientSanctuary"] =  { "Continent", "South Continent" },
    ["EXIT_SideLevel_RedForest"] =  { "Continent", "South Continent" },
    ["EXIT_EsquieNest"] =  { "Continent", "South Continent" },
    ["EXIT_SeaCliff"] =  { "Continent", "South Continent" },
    ["EXIT_GestralVillage"] =  { "Continent", "South Continent" },
    ["EXIT_Lumiere"] =  { "Continent", "South Continent" },
    ["EXIT_SideLevel_YellowForest"] =  { "Continent", "South Continent" },
    ["EXIT_SideLevel_DarkShores"] =  { "Continent", "South Continent" },
    ["EXIT_SmallLevel_CaveAbbest"] = { "Continent", "South Continent" },
    ["EXIT_MiniLevel_GestralTreeCity"] = { "Continent", "South Continent" },
    ["EXIT_MiniLevel_Spring"] = { "Continent", "South Continent" },
    ["EXIT_MiniLevel_BoatGraveyardBlue"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_GoblusLair_02"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_RedWoods"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_SpringMeadows"] = { "Continent", "South Continent" },
    ["EXIT_MiniLevel_WhiteTree"] = { "Continent", "South Continent" },
    ["EXIT_SideLevel_CleasTower_Entrance"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_StonewaveCliffsCave"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_FlyingCasinoEntrance"] = { "Continent", "South Continent" },
    ["EXIT_SmallLevel_CavernCrusher"] = { "Continent", "South Continent" },
    ["EXIT_MiniLevel_CleasOrangeArea"] = { "Continent", "South Continent" },
    ["EXIT_SideLevel_VersosDraft"] = { "Continent", "South Continent"},

    --Middle Continent
    ["EXIT_SideLevel_OrangeForest"] =  { "Continent", "Middle Continent" },
    ["EXIT_SideLevel_CleasFlyingHouse"] =  { "Continent", "Middle Continent" },
    ["EXIT_ForgottenBattlefield"] =  { "Continent", "Middle Continent" },
    ["EXIT_SidelLevel_FrozenHearts"] =  { "Continent", "Middle Continent" },
    ["EXIT_OldLumiere"] =  { "Continent", "Middle Continent" },
    ["EXIT_MonocoStation"] =  { "Continent", "Middle Continent" },
    ["EXIT_SideLevel_TwilightSanctuary"] =  { "Continent", "Middle Continent" },
    ["EXIT_MiniLevel_BladesGraveyard"] = { "Continent", "Middle Continent" },
    ["EXIT_MiniLevel_BoatGraveyardPurple"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_CoastalCave"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_StoneQuarry"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_TheCarrousel"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_SacredRiver"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_DoorMaze"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_ChosenPath"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_ChromaZoneEntry"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_WhiteSands"] = { "Continent", "Middle Continent" },
    ["EXIT_SmallLevel_FloatingIsland"] = { "Continent", "Middle Continent" },
    
    --North Continent
    ["EXIT_Monolith_Interior_PaintressIntro"] =  { "Continent", "North Continent" },
    ["EXIT_Monolith_Interior_Climb"] =  { "Continent", "North Continent" },
    ["EXIT_SideLevel_Reacher"] =  { "Continent", "North Continent" },
    ["EXIT_SideLevel_AxonPath"] =  { "Continent", "North Continent" },
    ["EXIT_SmallLevel_SimonArea"] =  { "Continent", "North Continent" },
    ["EXIT_Sirene"] =  { "Continent", "North Continent" },
    ["EXIT_Visages"] =  { "Continent", "North Continent" },
    ["EXIT_SmallLevel_SinisterCave"] = { "Continent", "North Continent" },
    ["EXIT_SmallLevel_TheCanvas"] = { "Continent", "North Continent" },
    ["EXIT_SmallLevel_Visages"] = { "Continent", "North Continent" },
    ["EXIT_SmallLevel_Reacher"] = { "Continent", "North Continent" }
}