FLAG_MAPPING = {
    ["Level_Main_ForgottenBattlefield_V2=>MainGate"] = { "@Entrance - Forgotten Battlefield/Flag - Main Gate" },
    ["Level_Main_ForgottenBattlefield_V2=>MainRuins"] = { "@Entrance - Forgotten Battlefield/Flag - Fort Ruins" },
    ["Level_Main_ForgottenBattlefield_V2=>SideBattlefield"] = { "@Entrance - Forgotten Battlefield/Flag - Battlefield" },
    ["Level_Main_ForgottenBattlefield_V2=>Battlefield"] = { "@Entrance - Forgotten Battlefield/Flag - Vanguard Point" },
    ["Level_Main_ForgottenBattlefield_V2=>DuallistArena"] = { "@Entrance - Forgotten Battlefield/Flag - Ancient Bridge" },
    ["Level_YellowForest_Main=>Lake"] = { "@Entrance - Yellow Harvest/Flag - Harvester's Hollow" },
    ["Level_YellowForest_Main=>Entry"] = { "@Entrance - Yellow Harvest/Flag - Entrance" },
    ["Level_YellowForest_Main=>Arena"] = { "@Entrance - Yellow Harvest/Flag - Yellow Spire Wrecks" },
    ["Level_OraneForest_Main=>CenterPlazza"] = { "@Entrance - Falling Leaves/Flag - Resinveil Grove" },
    ["Level_OraneForest_Main=>Scavenger"] = { "@Entrance - Falling Leaves/Flag - Scavenger" },
    ["Level_Reacher_Main_V2=>Entry"] = { "@Entrance - Reacher/Flag - Entrance" },
    ["Level_Reacher_Main_V2=>LadderArea"] = { "@Entrance - Reacher/Flag - Ladder Area" },
    ["Level_Reacher_Main_V2=>Mountain"] = { "@Entrance - Reacher/Flag - Mountain" },
    ["Level_Reacher_Main_V2=>FogArea"] = { "@Entrance - Reacher/Flag - Foggy Area" },
    ["Level_Reacher_Main_V2=>MountainTop"] = { "@Entrance - Reacher/Flag - Peak" },
    ["Level_Reacher_Main_V2=>Alicia"] = { "@Entrance - Reacher/Flag - Alicia" },
    ["Level_Cave_AbbestAlpha=>Arena"] = { "@Entrance - Abbest Cave/Chromatic Abbest" },
    ["SmallLevel_SimonArea=>Abyss"] = { "@Entrance - Renoir's Drafts/Flag - The Abyss" },
    ["Manor_Main_WP=>Entrance"] = { "Not Implemented" },
    ["Level_Visages_Main_V1=>Anger"] = { "@Entrance - Visages/Flag - Anger Vale" },
    ["Level_Visages_Main_V1=>Sadness"] = { "@Entrance - Visages/Flag - Sadness Vale" },
    ["Level_Visages_Main_V1=>Joy"] = { "@Entrance - Visages/Flag - Joy Vale" },
    ["Level_Visages_Main_V1=>Plazza"] = { "@Entrance - Visages/Flag - Plazza" },
    ["Level_Visages_Main_V1=>VisagesArena"] = { "@Entrance - Visages/Flag - Peak" },
    ["Level_Monolith_Exterior_Peak_Main=>Entry"] = { "Not Implemented" },
    ["Level_Monolith_Interior_Climb_Main=>Entry"] = { "@Entrance - The Monolith/Flag - Entrance" },
    ["Level_Monolith_Interior_Climb_Main=>SpringMeadows"] = { "@Entrance - The Monolith/Flag - Tainted Meadows" },
    ["Level_Monolith_Interior_Climb_Main=>Goblu"] = { "@Entrance - The Monolith/Flag - Tainted Waters" },
    ["Level_Monolith_Interior_Climb_Main=>AncientSanctuary"] = { "@Entrance - The Monolith/Flag - Tainted Sanctuary" },
    ["Level_Monolith_Interior_Climb_Main=>SeaCliff"] = { "@Entrance - The Monolith/Flag - Tainted Cliffs" },
    ["Level_Monolith_Interior_Climb_Main=>ForgottenBattlefield"] = { "@Entrance - The Monolith/Flag - Tainted Battlefield" },
    ["Level_Monolith_Interior_Climb_Main=>MonocoMountain"] = { "@Entrance - The Monolith/Flag - Tainted Hearts" },
    ["Level_Monolith_Interior_Climb_Main=>Lumiere"] = { "@Entrance - The Monolith/Flag - Tainted Lumiere" },
    ["Level_Monolith_Interior_Climb_Main=>RenoirArena"] = { "@Entrance - The Monolith/Flag - Peak" },
    ["LevelMain_EsquieNest=>GestralEntry"] = { "@Entrance - Esquie's Nest/Flag - Entrance" },
    ["LevelMain_EsquieNest=>Francois"] = { "@Entrance - Esquie's Nest/Flag - Francois" },
    ["Level_AncientSanctuary_Main_V2=>RedForest"] = { "@Entrance - Ancient Sanctuary/Flag - Entrance" },
    ["Level_AncientSanctuary_Main_V2=>TanksArena"] = { "@Entrance - Ancient Sanctuary/Flag - Sanctuary Maze" },
    ["Level_AncientSanctuary_Main_V2=>Arena"] = { "@Entrance - Ancient Sanctuary/Flag - Giant Bell Alley" },
    ["Level_AncientSanctuary_Main_V2=>GestralTotem"] = { "@Entrance - Ancient Sanctuary/Flag - Gestral Totem" },
    ["Level_Side_TwilightSanctuary=>Entry"] = { "@Entrance - Endless Night Sanctuary/Flag - Entrance" },
    ["Level_Side_TwilightSanctuary=>Arena"] = { "@Entrance - Endless Night Sanctuary/Flag - Warrior's Route" },
    ["Level_Side_TwilightSanctuary=>Totem"] = { "@Entrance - Endless Night Sanctuary/Flag - Night Totem" },
    ["Level_Sirene_Main_V2=>Ballet"] = { "@Entrance - Sirene/Flag - Dancing Classes" },
    ["Level_Sirene_Main_V2=>Couturier"] = { "@Entrance - Sirene/Flag - Sewing Atelier" },
    ["Level_Sirene_Main_V2=>Glissando"] = { "@Entrance - Sirene/Flag - Crumbling Path" },
    ["Level_Sirene_Main_V2=>SirenArena"] = { "@Entrance - Sirene/Flag - Dancing Arena" },
    ["Level_OldLumiere_Main=>BrokenBuildings"] = { "@Entrance - Old Lumiere/Flag - Entrance" },
    ["Level_OldLumiere_Main=>LunePath"] = { "@Entrance - Old Lumiere/Flag - Right Street" },
    ["Level_OldLumiere_Main=>MaellePath"] = { "@Entrance - Old Lumiere/Flag - Left Street" },
    ["Level_OldLumiere_Main=>ManorArena"] = { "@Entrance - Old Lumiere/Flag - Manor Gardens" },
    ["Level_OldLumiere_Main=>AlphaArea"] = { "@Entrance - Old Lumiere/Flag - Train Station Ruins"},
    ["Level_Goblu_Main_V5=>LimonsolHome"] = { "@Entrance - Flying Waters/Flag - Noco's Hut" },
    ["Level_Goblu_Main_V5=>CrulerCave"] = { "@Entrance - Flying Waters/Flag - Coral Cave" },
    ["Level_Goblu_Main_V5=>LumiereStreet"] = { "@Entrance - Flying Waters/Flag - Lumerian Streets" },
    ["Level_Goblu_Main_V5=>GobluArena"] = { "@Entrance - Flying Waters/Flag - Flower Fields" },
    ["Level_Monolith_Floor_1=>VistaEntrance"] = { "@Entrance - Renoir's Drafts/Flag - Entrance" },
    ["Level_Monolith_Floor_1=>SavepointEnd"] = { "@Entrance - Renoir's Drafts/Flag - Golden Tree" },
    ["Level_Side_CleasWorkShop_V2=>BrokenLampmaster"] = { "Not Implemented" },
    ["Level_Side_CleasTower=>Entrance"] = { "Not Implemented" },
    ["Level_PaintressIntro_Main=>Entry"] = { "Not Implemented" },
    ["Level_Main_GestralVillage_V2=>VillageEntry"] = { "@Entrance - Gestral Village/Flag - Gestral Village" },
    ["Level_Main_GestralVillage_V2=>GestralArena"] = { "@Entrance - Gestral Village/Flag - Gestral Arena" },
    ["Level_SpringMeadows_Main_V2=>MeadowsCorridor"] = { "@Entrance - Spring Meadows/Flag - Meadows Corridor" },
    ["Level_SpringMeadows_Main_V2=>GrandArea"] = { "@Entrance - Spring Meadows/Flag - Grand Meadow" },
    ["Level_SpringMeadows_Main_V2=>OldExpeditionnerCamp"] = { "@Entrance - Spring Meadows/Flag - Abandoned Expeditioner Camp" },
    ["Level_SpringMeadows_Main_V2=>Eveque"] = { "@Entrance - Spring Meadows/Flag - The Indigo Tree" },
    ["Level_RedForest_Main=>Plazza"] = { "@Entrance - Crimson Forest/Flag - Crimson Perch" },
    ["Level_RedForest_Main=>TheThreeBlades"] = { "@Entrance - Crimson Forest/Flag - The Three Blades" },
    ["Level_Camp_Main=>Entry"] = { "Not Implemented" },
    ["Level_SeaCliff_Main_V2=>ZeppelinEntry"] = { "@Entrance - Stone Wave Cliffs/Flag - Entrance" },
    ["Level_SeaCliff_Main_V2=>PaintressShrine"] = { "@Entrance - Stone Wave Cliffs/Flag - Paintress Shrine" },
    ["Level_SeaCliff_Main_V2=>Village"] = { "@Entrance - Stone Wave Cliffs/Flag - Old Farm" },
    ["Level_SeaCliff_Main_V2=>Caves"] = { "@Entrance - Stone Wave Cliffs/Flag - Tide Caverns" },
    ["Level_SeaCliff_Main_V2=>BasaltWaves"] = { "@Entrance - Stone Wave Cliffs/Flag - Basalt Waves" },
    ["Level_SeaCliff_Main_V2=>FloodedBuildings"] = { "@Entrance - Stone Wave Cliffs/Flag - Flooded Buildings" },
    ["Level_CleaFlyingHouse_Main=>Center"] = { "@Entrance - Flying Manor/Flag - Central Plaza" },
    ["Level_Lumiere_Main_V2=>Dock"] = { "@Entrance - Lumiere/Flag - Harbour" },
    ["Level_Lumiere_Main_V2=>BigPlazza"] = { "@Entrance - Lumiere/Flag - Central Plaza" },
    ["Level_Lumiere_Main_V2=>CrumblingBuildings"] = { "@Entrance - Lumiere/Flag - Shattered Alley" },
    ["Level_Lumiere_Main_V2=>Opera"] = { "@Entrance - Lumiere/Flag - Opera House" },
    ["Level_Lumiere_Main_V2=>Gardens"] = { "@Entrance - Lumiere/Flag - Lumiere's Garden" },
    ["Level_Lumiere_Main_V2=>Curator"] = { "@Entrance - Lumiere/Flag - Crooked Tower Walkway" },
    ["Level_MonocoStation=>IceCorridor"] = { "@Entrance - Monoco's Station/Flag - Ice corridor" },
    ["Level_MonocoStation=>InsideStation"] = { "@Entrance - Monoco's Station/Flag - Monoco's Station" },
    ["SmallLevel_YF_Zone_01=>Entry"] = { "Not Implemented" },
    ["Level_Side_FrozenHeart=>TrainStation"] = { "@Entrance - Frozen Hearts/Flag - Icebound Train Station" },
    ["Level_Side_FrozenHeart=>CaveStation"] = { "@Entrance - Frozen Hearts/Flag - Icebound Terminal" },
    ["Level_Side_FrozenHeart=>CaveForest"] = { "@Entrance - Frozen Hearts/Flag - Iced Heart" },
    ["Level_Side_FrozenHeart=>Frozenlakes"] = { "@Entrance - Frozen Hearts/Flag - Glacial Falls" }
    
}